# -*- coding: utf-8 -*-
"""Bilingual content model. Arabic is composed natively, not machine-translated.
Libya uses Western numerals (0-9), so all figures stay in 0-9 in both scripts."""

PAGES = ['index', 'services', 'ega-master', 'well-services', 'about', 'contact']

# ============================================================== SHARED FACTS
FACTS = dict(
    phone1='+218 21 732 5270',
    phone2='+218 91 650 7774',
    email='info@remalnahya.com',
    site='www.remalnahya.com',
)

# ============================================================== ENGLISH
EN = {
'lang': 'en', 'dir': 'ltr', 'other': 'ar', 'other_label': 'العربية',
'brand': 'Remal Nahya', 'brand_full': 'Remal Nahya for Oil Services',

'nav': {
    'index': 'Home', 'services': 'Services', 'ega-master': 'EGA Master Tools',
    'well-services': 'Well Services', 'about': 'About', 'contact': 'Contact',
},
'cta_nav': 'Request a quote',

'titles': {
  'index': 'Remal Nahya for Oil Services | Exclusive EGA Master Distributor in Libya',
  'services': 'Services | Certified Tools, Technical Procurement & Well Services — Remal Nahya',
  'ega-master': 'EGA Master Tools in Libya | ATEX & Non-Sparking — Remal Nahya',
  'well-services': 'Well Services | Cementing, Stimulation, Drilling & Intervention — Remal Nahya',
  'about': 'About Us | Libyan Expertise, Global Standards — Remal Nahya',
  'contact': 'Contact | Tripoli, Libya — Remal Nahya for Oil Services',
},
'descs': {
  'index': 'The exclusive EGA Master distributor in Libya. 20,000+ ATEX-certified and non-sparking tools held in country, technical procurement to the wellsite, and well services delivered to 15,000 psi with Rompetrol, SCA-Sichuan, Christof Industries and CONSTECHNO AL.',
  'services': 'Three pillars: certified industrial tool supply, technical procurement from order to wellsite, and partner-underwritten well services across cementing, stimulation, drilling, completion and intervention.',
  'ega-master': 'Remal Nahya is the exclusive EGA Master distributor in Libya. Non-sparking Cu-Be and Al-Bronze tools, ATEX safety sets, 1000V insulated tools, hydraulic and pipe tools — certified to ISO 9001, TÜV Rheinland, ATEX, IECEx, VDE and BAM.',
  'well-services': 'Primary and remedial cementing to 15,000 psi, matrix acidising, directional and extended-reach drilling, completion, workover, drilling fluids, nitrogen, slickline, casing running and drone pipeline and gas-leak survey.',
  'about': 'A Libyan oil services company built as the trusted bridge between international expertise and Libyan field operations, through active partnerships across Europe, Asia and the Mediterranean.',
  'contact': 'Gergarish Main Road, Hay Al-Andalus, Tripoli, Libya. Direct desks for tools, procurement, well services and drone survey.',
},

'depots': ['TRIPOLI · HQ', 'SIRTE BASIN', 'MURZUQ', 'GHADAMES'],

# ---------------- HOME
'hero': {
  'badge': 'Exclusive EGA Master distributor — Libya',
  'h1_a': 'Certified.', 'h1_b': 'In country.', 'h1_c': 'On the well.',
  'lede': 'Remal Nahya holds 20,000+ ATEX-certified and non-sparking tools in Libya, moves technical procurement from order to wellsite, and delivers well services to 15,000 psi with four international partners.',
  'cta1': 'Request a quote', 'cta2': 'Explore capabilities',
},
'stats': [
  dict(n=20000, group=1, post='+', label='EGA Master tool references'),
  dict(n=15000, group=1, post=' psi', label='Cementing pressure rating'),
  dict(n=4, group=0, post='', label='International service partners'),
  dict(n=1990, group=0, post='', label='EGA Master manufacturing since'),
],
'ticker': ['ISO 9001', 'TÜV Rheinland', 'ATEX', 'IECEx', 'VDE', 'BAM',
           'Rompetrol Well Services', 'SCA-Sichuan', 'Christof Industries', 'CONSTECHNO AL',
           'EGA Master — Exclusive Libya', 'Non-sparking Cu-Be', '15,000 psi cementing',
           'Drone VOC · H2S · SO2 survey'],

'pillars_eyebrow': '01 — What we do',
'pillars_h': 'Three pillars, one accountable supplier.',
'pillars_lede': 'Most operators in Libya buy tools from one company, procure consumables from a second, and contract well services from a third. We are all three, under one contract and one HSE standard.',
'pillars': [
  dict(idx='01', icon='tools', h='Certified tool supply',
       p='Exclusive EGA Master distribution in Libya. Non-sparking, ATEX, 1000V insulated, hydraulic and pipe tools — held in stock in Tripoli, not quoted from a catalogue abroad.',
       li=['20,000+ references across 12 industrial ranges',
           'Non-sparking Cu-Be and Al-Bronze for zoned areas',
           'Tool control systems and 5S foam kitting'],
       link='ega-master', cta='EGA Master in Libya'),
  dict(idx='02', icon='cart', h='Technical procurement',
       p='Sourcing, vendor qualification, import and customs clearance for industrial tools and field consumables — delivered from the order desk to the wellsite.',
       li=['Vendor qualification against operator specifications',
           'Import, clearance and inland transport handled in-house',
           'Field consumables, PPE and calibration services'],
       link='services', cta='How procurement works'),
  dict(idx='03', icon='box', h='Well services',
       p='Cementing, stimulation, drilling, completion and intervention, underwritten by Rompetrol Well Services, SCA-Sichuan, Christof Industries and CONSTECHNO AL.',
       li=['Primary and remedial cementing to 15,000 psi',
           'Directional and extended-reach horizontal drilling',
           'Drone pipeline and gas-leak survey without shutdown'],
       link='well-services', cta='Well services catalogue'),
],

'excl': {
  'eyebrow': '02 — Authorised distribution',
  'h': 'The only authorised route to EGA Master in Libya.',
  'quote': 'Remal Nahya is the exclusive authorised distributor of EGA Master in Libya, covering the full industrial and safety tool range on an exclusive basis for the Libyan market.',
  'p': 'EGA Master is a Spanish manufacturer, building industrial and safety tools in Vitoria-Gasteiz since 1990 and trusted by energy and petrochemical operators in over 100 countries. Every tool we supply arrives with its manufacturer certification intact — not a re-boxed equivalent, not a parallel import.',
  'meta': [dict(b='20,000+', s='Tool references'), dict(b='100+', s='Countries served'), dict(b='1990', s='Manufacturing since')],
  'certs': ['ISO 9001', 'TÜV Rheinland', 'ATEX', 'IECEx', 'VDE', 'BAM'],
  'cta': 'See the tool range',
},

'well_sec': {
  'eyebrow': '03 — Across the well lifecycle',
  'h': 'One well. Every stage.',
  'lede': 'Scroll the wellbore. Each stage below maps to a service our partners deliver in Libya, from the first cement job to the last intervention.',
  'cta': 'Full well services catalogue',
},
'well_steps': [
  dict(stage='cementing', n='01', h='Primary & remedial cementing',
       p='Zonal isolation and casing support from spud through to remedial squeeze work, executed to a pressure rating of 15,000 psi.',
       spec='15,000 psi', by='Rompetrol Well Services'),
  dict(stage='stimulation', n='02', h='Matrix acidising & stimulation',
       p='Acid stimulation designed for the formation — restoring and improving productivity in damaged or tight carbonate and sandstone reservoirs.',
       spec='Matrix & fracture acidising', by='Rompetrol Well Services'),
  dict(stage='completion', n='03', h='Completion & production optimisation',
       p='Running and setting the completion string, packers and downhole hardware, then optimising the well for sustained production.',
       spec='Packer & tubing installation', by='SCA-Sichuan'),
  dict(stage='intervention', n='04', h='Workover, slickline & nitrogen',
       p='Well re-entry, rehabilitation and intervention — slickline conveyance, nitrogen lifting and workover programmes on live and suspended wells.',
       spec='Slickline · N2 · Workover', by='Rompetrol · SCA-Sichuan'),
],

'partners': {
  'eyebrow': '04 — Strategic partners',
  'h': 'Our partners are our capability.',
  'lede': 'Well services are not subcontracted out of sight. Each service below is underwritten by a named partner with an active agreement, so you know exactly whose engineering stands behind the job.',
},
'partner_list': [
  dict(n='01', h='Rompetrol Well Services', c='Romania',
       p='Pressure pumping specialists covering cementing, matrix and fracture acidising, drilling fluids for high-pressure formations, and nitrogen and slickline services.',
       tags=['Cementing 15,000 psi', 'Acid stimulation', 'Drilling fluids', 'Nitrogen · Slickline']),
  dict(n='02', h='SCA-Sichuan', c='China',
       p='Drilling and completion contractor delivering directional and extended-reach horizontal wells, completion programmes and workover and re-entry campaigns.',
       tags=['Directional drilling', 'Extended-reach', 'Completion', 'Workover']),
  dict(n='03', h='Christof Industries', c='Austria',
       p='Industrial plant and inspection engineering, supplying our unmanned survey capability — pipeline inspection and hydrocarbon gas-leak detection carried out without stopping operations.',
       tags=['Drone pipeline inspection', 'VOC · H2S · SO2 survey', 'Plant engineering']),
  dict(n='04', h='CONSTECHNO AL', c='Mediterranean',
       p='Tubular running services — casing and liner running, handling and setting, with the equipment spread and crews mobilised to the rig site.',
       tags=['Casing running', 'Liner setting', 'Tubular handling']),
],

'drone': {
  'eyebrow': '05 — Unmanned survey',
  'h': 'Find the leak without shutting the line.',
  'lede': 'Hydrocarbon leaks are invisible until they are expensive. Our drone survey carries gas-detection sensors over live pipelines and facilities, flagging VOC, H₂S and SO₂ releases while the asset stays in production.',
  'li': ['Pipeline right-of-way inspection across remote spreads',
         'VOC, H₂S and SO₂ leak detection while the line stays live',
         'Georeferenced findings mapped to pipeline chainage',
         'Supports leak detection and repair (LDAR) programmes'],
  'cta': 'Discuss a survey',
  'by': 'Delivered with Christof Industries',
},

'map': {
  'eyebrow': '06 — Coverage',
  'h': 'Based in Tripoli. Mobilised to the basin.',
  'lede': 'Our warehouse and order desk sit on Gergarish Main Road in Tripoli, with tools held in country rather than quoted from abroad. Crews and equipment mobilise to the Sirte, Murzuq, Ghadames and Cyrenaica basins.',
  'li': ['Stock held in Tripoli — no import lead time on catalogue items',
         'Import, customs clearance and inland transport handled in-house',
         'Partner crews and equipment spreads mobilised to the rig site'],
  'cta': 'Contact the Tripoli desk',
},

'cta_band': {
  'h': 'Send the specification. Get back the certification.',
  'p': 'Tell us the hazard zone, the standard you work to, and the delivery point. You will get a quote with the manufacturer certification attached — not a promise to source it later.',
  'b1': 'Request a quote', 'b2': 'Call the Tripoli desk',
},

# ---------------- SERVICES PAGE
'services_head': {
  'h': 'Everything from the tool crib to the wellhead.',
  'lede': 'Twenty-four services across three pillars. Filter by what you need, or search the catalogue.',
},
'filter_labels': dict(all='All services', tools='Certified tools', procurement='Procurement', wells='Well services', drone='Drone survey'),
'search_ph': 'Search services…',
'lead': {
  'eyebrow': 'Lead time',
  'h': 'How long it actually takes.',
  'lede': 'The reason to hold stock in country is that an import cycle costs weeks a rig does not have. Indicative timings, confirmed against the actual line items at quotation.',
  'rows': [
    dict(k='From Tripoli stock', v='48 hours', d='To a Tripoli delivery point. 3–5 days to the Sirte, Murzuq or Ghadames basins.', tag='No import cycle'),
    dict(k='Standard import', v='3–4 weeks', d='Catalogue items not held in country — sourcing, import, clearance and inland transport handled in-house.', tag='One accountable party'),
    dict(k='Special alloy or made to order', v='Quoted per item', d='Non-standard sizes, special alloys and custom kitting, against the manufacturer lead time.', tag='Manufacturer lead time'),
  ],
},

# ---------------- EGA PAGE
'ega_head': {
  'h': 'EGA Master, held in Libya.',
  'lede': 'Exclusive distribution of the full EGA Master range — non-sparking, ATEX, insulated, hydraulic and pipe tools — with manufacturer certification intact.',
},
'ega_risk': {
  'eyebrow': 'Why certified tools',
  'h': 'In a zoned area, the tool is the ignition source.',
  'p': 'Working with hydrocarbons carries risks with human, environmental and economic consequences that do not scale down. A standard steel wrench dropped on a flanged joint in a Zone 1 area is a spark. Certified non-sparking tools remove that variable from the job — and the certificate is what your HSE auditor asks to see, not the tool.',
  'li': ['Copper-beryllium and aluminium-bronze alloys that do not spark on impact',
         'ATEX and IECEx marking for explosive atmospheres',
         '1000V insulated tools tested to VDE for live electrical work',
         'Anti-drop tethering for work at height over live plant'],
},
'ega_cats': [
  dict(art='atex', h='Non-sparking tools', p='Cu-Be and Al-Bronze hand tools for Zone 0, 1 and 2 areas — wrenches, hammers, sockets, scrapers and chisels that will not generate an incendive spark on impact.', tag='ATEX · IECEx'),
  dict(art='wrench', h='ATEX safety sets', p='Pre-packaged maintenance kits assembled for hazardous-area work, supplied as a certified set with the tool list and certification documented per kit.', tag='Certified sets'),
  dict(art='socket', h='Insulated 1000V tools', p='VDE-tested insulated hand tools for live electrical work, including combined 1000V insulated and non-sparking tools for dual-hazard environments.', tag='VDE 1000V'),
  dict(art='hydraulic', h='Hydraulic & torque tools', p='Hydraulic torque wrenches, bolt tensioners, pullers and presses for flange management, plus calibrated torque control for critical joints.', tag='Calibrated'),
  dict(art='pipe', h='Pipe tools & machines', p='Pipe wrenches, cutters, threading and bevelling machines and tube benders for pipeline, refinery and plant fabrication work.', tag='Pipeline'),
  dict(art='socket', h='Tool control & 5S kitting', p='Foam-cut tool trays and shadow boards that make a missing tool visible at a glance — the difference between a tool count and a dropped-object incident.', tag='Tool control'),
],
'ega_stats_h': 'What sits behind the brand.',
'ega_stats': [
  dict(n=20000, group=1, post='+', label='Tool references in range'),
  dict(n=12, group=0, post='', label='Industrial tool ranges'),
  dict(n=100, group=0, post='+', label='Countries supplied'),
  dict(n=200, group=0, post='+', label='Registered patents'),
],
'ega_cta': {'h': 'Tell us the zone and the standard.',
            'p': 'Send your hazard classification and the standard you work to. We will come back with the exact EGA Master references, the certification, and availability from Tripoli stock.',
            'b1': 'Request the catalogue', 'b2': 'Email the tools desk'},

# ---------------- WELL SERVICES PAGE
'ws_head': {
  'h': 'Well services, underwritten by name.',
  'lede': 'Ten services across the well lifecycle, each delivered under an active agreement with a named international partner.',
},
'ws_apps_h': 'Typical applications.',
'ws_apps': ['New well construction and completion campaigns',
            'Remedial and squeeze cementing on existing wells',
            'Productivity restoration in damaged carbonate and sandstone reservoirs',
            'Extended-reach and horizontal development drilling',
            'Live-well intervention, re-entry and rehabilitation',
            'Pipeline integrity and fugitive emissions survey without shutdown'],

# ---------------- ABOUT
'about_head': {'h': 'Libyan expertise. Global standards.',
               'lede': 'A Libyan oil services company built to be the trusted bridge between international engineering and Libyan field operations.'},
'about_who': {
  'eyebrow': 'Who we are',
  'h': 'The bridge, not the middleman.',
  'p1': 'Remal Nahya for Oil Services is a Libyan company specialising in integrated oilfield services — from technical procurement and certified industrial tool supply through to well services and upstream and downstream operations.',
  'p2': 'We represent the trusted local bridge between international expertise and Libyan oil operations, through active partnerships across Europe, Asia and the Mediterranean, bringing the best global oilfield technologies and services into the Libyan energy sector.',
  'p3': 'The distinction matters. A middleman forwards an enquiry and adds a margin. A bridge holds stock in country, carries the manufacturer authorisation, mobilises the partner crew, and stands behind the job when the rig is waiting.',
},
'about_mv': [
  dict(k='Mission', v='To deliver trusted energy and industrial solutions built for Libya’s evolving oil and gas sector — bringing world-class tools and international safety standards to operators working here.'),
  dict(k='Vision', v='To become a leading force in Libya’s energy sector — measured against the same standards an operator would apply anywhere else in the world.'),
],
'about_vals_h': 'What we will not trade away.',
'about_vals': [
  dict(n='01', h='Safety', p='A zero-compromise safety culture. Certified tools, certified crews, and the certificate available before the job starts — not after an audit asks for it.'),
  dict(n='02', h='Quality', p='High-precision, certified equipment supplied with its manufacturer documentation intact. No re-boxed equivalents, no parallel imports.'),
  dict(n='03', h='Integrity', p='Named partners, dated agreements, and scope we can actually deliver. If a job is outside what we can stand behind, we say so.'),
  dict(n='04', h='Partnership', p='Relationships built on trust rather than transactions. Operators here work with the same people for decades — we intend to be one of them.'),
],
'about_tl_h': 'How a job actually runs.',
'about_tl': [
  dict(b='STEP 01', h='Specification', p='You send the hazard zone, the standard, the quantity and the delivery point. For well services, the well programme and the formation.'),
  dict(b='STEP 02', h='Quote with certification', p='We come back with exact references, the manufacturer certification attached, availability from Tripoli stock, and a delivered price — not an indicative one.'),
  dict(b='STEP 03', h='Import, clearance, transport', p='Where an item is not in stock, import, customs clearance and inland transport are handled in-house. One point of accountability, not a chain of forwarders.'),
  dict(b='STEP 04', h='Mobilisation', p='For well services, the partner crew and equipment spread mobilise to the rig site under our contract and our HSE standard.'),
  dict(b='STEP 05', h='After the job', p='Warranty, calibration and re-order handled from the same desk that quoted it. The people who sold it are the people who answer the phone.'),
],

# ---------------- CONTACT
'contact_head': {'h': 'Talk to the right desk.',
                 'lede': 'Route your enquiry to the team that handles it. No general inbox, no forwarding chain.'},
'desks_h': 'Direct desks',
'desks': [
  dict(b='Certified tools & EGA Master', s='tools@remalnahya.com'),
  dict(b='Technical procurement', s='procurement@remalnahya.com'),
  dict(b='Well services', s='wellservices@remalnahya.com'),
  dict(b='Drone survey & inspection', s='survey@remalnahya.com'),
],
'desks_note': 'Proposed routing. Until the departmental mailboxes are live, all four forward to info@remalnahya.com.',
'contact_rows_h': 'Head office',
'form_h': 'Request a quote',
'form_lede': 'Tell us what you need and where it is going. We reply within one working day.',
'form': dict(name='Full name', company='Company', email='Email', phone='Phone',
             dept='Enquiry type', msg='What do you need?',
             msg_ph='Hazard zone, standard, quantities, delivery point — or the well programme.',
             file='Attach a specification or BOQ', file_hint='PDF, XLSX, CSV or DWG — up to 20 MB. Optional.',
             ph_name='Ahmed Al-…', ph_co='Operator or contractor name',
             submit='Send enquiry',
             ok='Thank you. Your enquiry has been recorded and routed to the right desk — we reply within one working day. (This is a demonstration form; no message was actually sent.)',
             note='We never share enquiry details with third parties.'),
'form_depts': ['Certified tools & EGA Master', 'Technical procurement', 'Well services', 'Drone survey & inspection', 'Partnership or supply', 'Something else'],

# ---------------- FOOTER
'foot': {
  'about': 'A Libyan oil services company: exclusive EGA Master distribution, technical procurement, and well services delivered with international partners.',
  'c1': 'Company', 'c2': 'Services', 'c3': 'Get in touch',
  'legal': '© 2026 Remal Nahya for Oil Services. All rights reserved.',
  'built': 'Concept — prepared for Remal Nahya, 2026',
},
'foot_services': [('ega-master', 'EGA Master tools'), ('services', 'Technical procurement'),
                  ('well-services', 'Well services'), ('well-services', 'Drone survey')],
'skip': 'Skip to content',
}


# ============================================================== ARABIC
AR = {
'lang': 'ar', 'dir': 'rtl', 'other': 'en', 'other_label': 'English',
'brand': 'رمال ناهية', 'brand_full': 'رمال ناهية للخدمات النفطية',

'nav': {
    'index': 'الرئيسية', 'services': 'خدماتنا', 'ega-master': 'أدوات EGA Master',
    'well-services': 'خدمات الآبار', 'about': 'من نحن', 'contact': 'تواصل معنا',
},
'cta_nav': 'اطلب عرض سعر',

'titles': {
  'index': 'رمال ناهية للخدمات النفطية | الموزّع الحصري لـ EGA Master في ليبيا',
  'services': 'خدماتنا | أدوات معتمدة ومشتريات تقنية وخدمات آبار — رمال ناهية',
  'ega-master': 'أدوات EGA Master في ليبيا | معتمدة ATEX وغير شرارية — رمال ناهية',
  'well-services': 'خدمات الآبار | تسمنت وتحفيز وحفر وتدخلات — رمال ناهية',
  'about': 'من نحن | كفاءة ليبية.. معايير دولية — رمال ناهية',
  'contact': 'تواصل معنا | طرابلس، ليبيا — رمال ناهية للخدمات النفطية',
},
'descs': {
  'index': 'الموزّع الحصري لـ EGA Master في ليبيا. أكثر من 20,000 أداة معتمدة وغير شرارية متوفرة داخل البلاد، ومشتريات تقنية من الطلب حتى موقع العمل، وخدمات آبار حتى 15,000 psi بالشراكة مع Rompetrol وSCA-Sichuan وChristof Industries وCONSTECHNO AL.',
  'services': 'ثلاثة محاور: توريد الأدوات الصناعية المعتمدة، والمشتريات التقنية من الطلب حتى موقع البئر، وخدمات آبار مدعومة باتفاقيات فاعلة تشمل التسمنت والتحفيز والحفر والإتمام والتدخلات.',
  'ega-master': 'رمال ناهية هي الموزّع الحصري لـ EGA Master في ليبيا. أدوات غير شرارية من سبائك النحاس-بريليوم والبرونز الألومنيومي، وأطقم سلامة ATEX، وأدوات معزولة 1000 فولت، وأدوات هيدروليكية وأنابيب — معتمدة من ISO 9001 وTÜV Rheinland وATEX وIECEx وVDE وBAM.',
  'well-services': 'تسمنت أولي وعلاجي حتى 15,000 psi، وتحفيز حمضي للمصفوفة، وحفر اتجاهي وأفقي ممتد المدى، وإتمام الآبار، وWorkover، وإدارة سوائل الحفر، وخدمات النيتروجين والـ Slickline، وتشغيل أعمدة التغليف، وفحص خطوط الأنابيب ورصد تسربات الغازات بالطائرات المسيّرة.',
  'about': 'شركة ليبية متخصصة في الخدمات النفطية المتكاملة، تمثّل الجسر المحلي الموثوق بين الخبرة الدولية والعمليات النفطية الليبية عبر شراكات فاعلة في أوروبا وآسيا والبحر المتوسط.',
  'contact': 'طريق قرقارش الرئيسي، حي الأندلس، طرابلس، ليبيا. مكاتب مباشرة للأدوات والمشتريات وخدمات الآبار والمسح بالطائرات المسيّرة.',
},

'depots': ['طرابلس · المقر', 'حوض سرت', 'مرزق', 'غدامس'],

'hero': {
  'badge': 'الموزّع الرسمي الحصري لـ EGA Master — ليبيا',
  'h1_a': 'معتمدة.', 'h1_b': 'داخل ليبيا.', 'h1_c': 'على رأس البئر.',
  'lede': 'رمال ناهية توفّر أكثر من 20,000 أداة معتمدة وغير شرارية داخل ليبيا، وتدير المشتريات التقنية من الطلب حتى موقع العمل، وتنفّذ خدمات آبار حتى 15,000 psi مع أربعة شركاء دوليين.',
  'cta1': 'اطلب عرض سعر', 'cta2': 'تعرّف على قدراتنا',
},
'stats': [
  dict(n=20000, group=1, post='+', label='مرجع أداة من EGA Master'),
  dict(n=15000, group=1, post=' psi', label='ضغط التسمنت المعتمد'),
  dict(n=4, group=0, post='', label='شركاء خدمات دوليون'),
  dict(n=1990, group=0, post='', label='EGA Master تصنّع منذ عام'),
],
'ticker': ['ISO 9001', 'TÜV Rheinland', 'ATEX', 'IECEx', 'VDE', 'BAM',
           'Rompetrol Well Services', 'SCA-Sichuan', 'Christof Industries', 'CONSTECHNO AL',
           'EGA Master — حصرياً في ليبيا', 'أدوات غير شرارية Cu-Be', 'تسمنت حتى 15,000 psi',
           'مسح VOC · H2S · SO2 بالطائرات المسيّرة'],

'pillars_eyebrow': '01 — ما نقدّمه',
'pillars_h': 'ثلاثة محاور، ومورّد واحد مسؤول.',
'pillars_lede': 'أغلب المشغّلين في ليبيا يشترون الأدوات من شركة، ويوردون المستلزمات من ثانية، ويتعاقدون على خدمات الآبار مع ثالثة. نحن الثلاثة معاً، تحت عقد واحد ومعيار سلامة واحد.',
'pillars': [
  dict(idx='01', icon='tools', h='توريد الأدوات المعتمدة',
       p='التوزيع الحصري لـ EGA Master في ليبيا. أدوات غير شرارية ومعتمدة ATEX ومعزولة 1000 فولت وهيدروليكية وأنابيب — متوفرة في مخازننا بطرابلس، لا مجرد عرض من كتالوج في الخارج.',
       li=['أكثر من 20,000 مرجع ضمن 12 مجموعة صناعية',
           'سبائك Cu-Be والبرونز الألومنيومي للمناطق المصنّفة',
           'أنظمة ضبط العدد وأطقم الإسفنج المقصوص 5S'],
       link='ega-master', cta='EGA Master في ليبيا'),
  dict(idx='02', icon='cart', h='المشتريات التقنية',
       p='تأمين المصادر وتأهيل الموردين والاستيراد والتخليص الجمركي للأدوات الصناعية ومستلزمات الحقل — من مكتب الطلب حتى موقع العمل.',
       li=['تأهيل الموردين وفق مواصفات المشغّل',
           'الاستيراد والتخليص والنقل الداخلي بإدارتنا المباشرة',
           'مستلزمات الحقل ومعدات الوقاية وخدمات المعايرة'],
       link='services', cta='كيف تعمل المشتريات'),
  dict(idx='03', icon='well', h='خدمات الآبار',
       p='التسمنت والتحفيز والحفر والإتمام والتدخلات، مدعومة باتفاقيات فاعلة مع Rompetrol Well Services وSCA-Sichuan وChristof Industries وCONSTECHNO AL.',
       li=['تسمنت أولي وعلاجي حتى 15,000 psi',
           'حفر اتجاهي وأفقي ممتد المدى',
           'فحص الأنابيب ورصد التسربات دون إيقاف العمليات'],
       link='well-services', cta='دليل خدمات الآبار'),
],

'excl': {
  'eyebrow': '02 — التوزيع المعتمد',
  'h': 'الطريق المعتمد الوحيد إلى EGA Master في ليبيا.',
  'quote': 'رمال ناهية هي الموزّع الرسمي الحصري لـ EGA Master في ليبيا، وتغطي المجموعة الكاملة من الأدوات الصناعية وأدوات السلامة على أساس حصري للسوق الليبي.',
  'p': 'EGA Master مصنّع إسباني يصنع الأدوات الصناعية وأدوات السلامة في فيتوريا-غاستيز منذ عام 1990، وتثق به شركات الطاقة والبتروكيماويات في أكثر من 100 دولة. كل أداة نوردها تصل بشهادة المصنّع كاملة — لا بديل معاد تغليفه، ولا استيراد مواز.',
  'meta': [dict(b='20,000+', s='مرجع أداة'), dict(b='100+', s='دولة'), dict(b='1990', s='تصنّع منذ عام')],
  'certs': ['ISO 9001', 'TÜV Rheinland', 'ATEX', 'IECEx', 'VDE', 'BAM'],
  'cta': 'تصفّح مجموعة الأدوات',
},

'well_sec': {
  'eyebrow': '03 — عبر دورة حياة البئر',
  'h': 'بئر واحد. كل المراحل.',
  'lede': 'تصفّح مقطع البئر. كل مرحلة أدناه تقابل خدمة ينفّذها شركاؤنا في ليبيا، من أول عملية تسمنت حتى آخر تدخل.',
  'cta': 'دليل خدمات الآبار الكامل',
},
'well_steps': [
  dict(stage='cementing', n='01', h='التسمنت الأولي والعلاجي',
       p='عزل الطبقات ودعم أعمدة التغليف من بداية الحفر حتى أعمال الحقن العلاجي، بضغط معتمد يصل إلى 15,000 psi.',
       spec='15,000 psi', by='Rompetrol Well Services'),
  dict(stage='stimulation', n='02', h='التحفيز الحمضي للمصفوفة',
       p='تحفيز حمضي مصمّم حسب التكوين — لاستعادة الإنتاجية وتحسينها في المكامن الكربوناتية والرملية المتضررة أو الضيقة.',
       spec='تحميض مصفوفي وتكسيري', by='Rompetrol Well Services'),
  dict(stage='completion', n='03', h='إتمام الآبار وتحسين الإنتاج',
       p='تشغيل وتثبيت عمود الإتمام والحواجز والمعدات الجوفية، ثم تحسين أداء البئر لإنتاج مستقر.',
       spec='تركيب Packer والأنابيب', by='SCA-Sichuan'),
  dict(stage='intervention', n='04', h='Workover والـ Slickline والنيتروجين',
       p='إعادة دخول الآبار وإعادة تأهيلها والتدخل فيها — نقل بالـ Slickline، ورفع بالنيتروجين، وبرامج Workover على الآبار العاملة والمعلّقة.',
       spec='Slickline · N2 · Workover', by='Rompetrol · SCA-Sichuan'),
],

'partners': {
  'eyebrow': '04 — الشركاء الاستراتيجيون',
  'h': 'شركاؤنا هم قدرتنا.',
  'lede': 'خدمات الآبار لا تُسنَد من الباطن بعيداً عن الأنظار. كل خدمة أدناه مدعومة بشريك مذكور بالاسم وباتفاقية فاعلة، لتعرف تحديداً أي هندسة تقف خلف العمل.',
},
'partner_list': [
  dict(n='01', h='Rompetrol Well Services', c='رومانيا',
       p='متخصصون في الضخ الضغطي، ويغطون التسمنت والتحميض المصفوفي والتكسيري، وسوائل الحفر للتكوينات عالية الضغط، وخدمات النيتروجين والـ Slickline.',
       tags=['تسمنت 15,000 psi', 'تحفيز حمضي', 'سوائل الحفر', 'نيتروجين · Slickline']),
  dict(n='02', h='SCA-Sichuan', c='الصين',
       p='مقاول حفر وإتمام ينفّذ الآبار الاتجاهية والأفقية ممتدة المدى، وبرامج الإتمام، وحملات Workover وإعادة الدخول.',
       tags=['حفر اتجاهي', 'ممتد المدى', 'إتمام الآبار', 'Workover']),
  dict(n='03', h='Christof Industries', c='النمسا',
       p='هندسة المنشآت الصناعية والفحص، وتوفّر قدرتنا في المسح بالطائرات المسيّرة — فحص خطوط الأنابيب ورصد تسربات الغازات الهيدروكربونية دون إيقاف العمليات.',
       tags=['فحص الأنابيب بالمسيّرات', 'مسح VOC · H2S · SO2', 'هندسة المنشآت']),
  dict(n='04', h='CONSTECHNO AL', c='البحر المتوسط',
       p='خدمات تشغيل الأنابيب — تشغيل وتثبيت أعمدة التغليف والـ Liner ومناولتها، مع تجهيزات وأطقم تُعبّأ إلى موقع الحفر.',
       tags=['تشغيل أعمدة التغليف', 'تثبيت الـ Liner', 'مناولة الأنابيب']),
],

'drone': {
  'eyebrow': '05 — المسح بالطائرات المسيّرة',
  'h': 'اعثر على التسرب دون إيقاف الخط.',
  'lede': 'تسربات الهيدروكربونات تبقى غير مرئية حتى تصبح مكلفة. مسحنا بالطائرات المسيّرة يحمل حساسات كشف الغازات فوق الخطوط والمنشآت العاملة، ويرصد انبعاثات VOC وH₂S وSO₂ والأصل ما زال في الإنتاج.',
  'li': ['فحص مسارات خطوط الأنابيب عبر مساحات نائية',
         'رصد تسربات VOC وH₂S وSO₂ والخط ما زال عاملاً',
         'نتائج مرجعية جغرافياً مربوطة بمواقع الخط',
         'يدعم برامج كشف التسربات وإصلاحها (LDAR)'],
  'cta': 'ناقش عملية مسح',
  'by': 'بالتعاون مع Christof Industries',
},

'map': {
  'eyebrow': '06 — التغطية',
  'h': 'مقرنا طرابلس. وتعبئتنا إلى الحوض.',
  'lede': 'مخزننا ومكتب الطلبات في طريق قرقارش الرئيسي بطرابلس، والأدوات محفوظة داخل البلاد لا معروضة من الخارج. الأطقم والمعدات تُعبّأ إلى أحواض سرت ومرزق وغدامس وبرقة.',
  'li': ['مخزون داخل طرابلس — دون مهلة استيراد لأصناف الكتالوج',
         'الاستيراد والتخليص الجمركي والنقل الداخلي بإدارتنا',
         'أطقم الشركاء وتجهيزاتهم تُعبّأ إلى موقع الحفر'],
  'cta': 'تواصل مع مكتب طرابلس',
},

'cta_band': {
  'h': 'أرسل المواصفة. استلم الشهادة.',
  'p': 'أخبرنا بتصنيف المنطقة الخطرة، والمعيار الذي تعمل به، ونقطة التسليم. ستحصل على عرض سعر بشهادة المصنّع مرفقة — لا وعد بتأمينها لاحقاً.',
  'b1': 'اطلب عرض سعر', 'b2': 'اتصل بمكتب طرابلس',
},

'services_head': {
  'h': 'من مخزن العدد حتى رأس البئر.',
  'lede': 'أربع وعشرون خدمة عبر ثلاثة محاور. صفِّ حسب ما تحتاجه، أو ابحث في الدليل.',
},
'filter_labels': dict(all='كل الخدمات', tools='الأدوات المعتمدة', procurement='المشتريات', wells='خدمات الآبار', drone='المسح بالمسيّرات'),
'search_ph': 'ابحث في الخدمات…',
'lead': {
  'eyebrow': 'مدة التوريد',
  'h': 'كم يستغرق الأمر فعلياً.',
  'lede': 'سبب الاحتفاظ بالمخزون داخل البلاد أن دورة الاستيراد تكلّف أسابيع لا تملكها الحفارة. المدد استرشادية، وتُؤكَّد على بنود الطلب الفعلية عند إصدار العرض.',
  'rows': [
    dict(k='من مخزون طرابلس', v='48 ساعة', d='إلى نقطة تسليم داخل طرابلس. ومن 3 إلى 5 أيام إلى أحواض سرت أو مرزق أو غدامس.', tag='دون دورة استيراد'),
    dict(k='استيراد اعتيادي', v='3–4 أسابيع', d='أصناف الكتالوج غير المتوفرة داخل البلاد — التأمين والاستيراد والتخليص والنقل الداخلي بإدارتنا.', tag='جهة مسؤولة واحدة'),
    dict(k='سبائك خاصة أو تصنيع حسب الطلب', v='حسب الصنف', d='المقاسات غير القياسية والسبائك الخاصة والأطقم المخصصة، وفق مدة تصنيع المصنّع.', tag='مدة تصنيع المصنّع'),
  ],
},

'ega_head': {
  'h': 'EGA Master، متوفرة داخل ليبيا.',
  'lede': 'توزيع حصري للمجموعة الكاملة من EGA Master — أدوات غير شرارية ومعتمدة ATEX ومعزولة وهيدروليكية وأنابيب — بشهادة المصنّع كاملة.',
},
'ega_risk': {
  'eyebrow': 'لماذا الأدوات المعتمدة',
  'h': 'في المنطقة المصنّفة، الأداة نفسها هي مصدر الاشتعال.',
  'p': 'العمل مع الهيدروكربونات ينطوي على مخاطر ذات عواقب بشرية وبيئية واقتصادية لا تصغر بصغر العمل. مفتاح فولاذي عادي يسقط على وصلة مفلنجة في منطقة Zone 1 يعني شرارة. الأدوات غير الشرارية المعتمدة تزيل هذا المتغيّر من المهمة — والشهادة هي ما يطلبه مدقّق السلامة، لا الأداة.',
  'li': ['سبائك النحاس-بريليوم والبرونز الألومنيومي لا تولّد شرراً عند الارتطام',
         'علامات ATEX وIECEx للأجواء القابلة للانفجار',
         'أدوات معزولة 1000 فولت مختبرة وفق VDE للأعمال الكهربائية الحية',
         'أنظمة تأمين ضد السقوط للعمل على ارتفاع فوق منشآت عاملة'],
},
'ega_cats': [
  dict(art='atex', h='الأدوات غير الشرارية', p='أدوات يدوية من Cu-Be والبرونز الألومنيومي لمناطق Zone 0 و1 و2 — مفاتيح ومطارق ولقم وكاشطات وأزاميل لا تولّد شرراً قادراً على الإشعال عند الارتطام.', tag='ATEX · IECEx'),
  dict(art='wrench', h='أطقم السلامة ATEX', p='أطقم صيانة معبأة مسبقاً ومجهزة للعمل في المناطق الخطرة، تُورَّد كطقم معتمد مع قائمة الأدوات والشهادات الموثّقة لكل طقم.', tag='أطقم معتمدة'),
  dict(art='socket', h='أدوات معزولة 1000 فولت', p='أدوات يدوية معزولة ومختبرة وفق VDE للأعمال الكهربائية الحية، بما فيها أدوات تجمع بين العزل 1000 فولت وخاصية عدم الشرر للبيئات مزدوجة الخطورة.', tag='VDE 1000V'),
  dict(art='hydraulic', h='الأدوات الهيدروليكية وأدوات العزم', p='مفاتيح عزم هيدروليكية وشادّات براغي وسحّابات ومكابس لإدارة الفلنجات، مع ضبط عزم معاير للوصلات الحرجة.', tag='معايرة'),
  dict(art='pipe', h='أدوات وماكينات الأنابيب', p='مفاتيح أنابيب وقاطعات وماكينات تسنين وشطب وثنّايات لأعمال خطوط الأنابيب والمصافي وتصنيع المنشآت.', tag='خطوط الأنابيب'),
  dict(art='socket', h='ضبط العدد وأطقم 5S', p='صواني إسفنجية مقصوصة ولوحات ظلّية تجعل الأداة المفقودة ظاهرة بنظرة واحدة — الفارق بين جرد للعدد وحادث سقوط أداة.', tag='ضبط العدد'),
],
'ega_stats_h': 'ما الذي يقف خلف العلامة',
'ega_stats': [
  dict(n=20000, group=1, post='+', label='مرجع أداة في المجموعة'),
  dict(n=12, group=0, post='', label='مجموعة أدوات صناعية'),
  dict(n=100, group=0, post='+', label='دولة يتم التوريد إليها'),
  dict(n=200, group=0, post='+', label='براءة اختراع مسجّلة'),
],
'ega_cta': {'h': 'أخبرنا بالمنطقة والمعيار.',
            'p': 'أرسل تصنيف المنطقة الخطرة والمعيار الذي تعمل به، ونعود إليك بالمراجع الدقيقة من EGA Master، والشهادات، وتوفرها من مخزون طرابلس.',
            'b1': 'اطلب الكتالوج', 'b2': 'راسل مكتب الأدوات'},

'ws_head': {
  'h': 'خدمات آبار مدعومة بالاسم.',
  'lede': 'عشر خدمات عبر دورة حياة البئر، كل منها ينفَّذ باتفاقية فاعلة مع شريك دولي مذكور بالاسم.',
},
'ws_apps_h': 'التطبيقات النموذجية',
'ws_apps': ['حملات إنشاء وإتمام الآبار الجديدة',
            'التسمنت العلاجي وأعمال الحقن على الآبار القائمة',
            'استعادة الإنتاجية في المكامن الكربوناتية والرملية المتضررة',
            'الحفر التطويري الأفقي وممتد المدى',
            'التدخل في الآبار العاملة وإعادة الدخول وإعادة التأهيل',
            'فحص سلامة خطوط الأنابيب ورصد الانبعاثات دون إيقاف العمليات'],

'about_head': {'h': 'كفاءة ليبية.. معايير دولية.',
               'lede': 'شركة خدمات نفطية ليبية بُنيت لتكون الجسر الموثوق بين الهندسة الدولية والعمليات الحقلية الليبية.'},
'about_who': {
  'eyebrow': 'من نحن',
  'h': 'الجسر، لا الوسيط.',
  'p1': 'رمال ناهية للخدمات النفطية شركة ليبية متخصصة في الخدمات النفطية المتكاملة — من المشتريات التقنية وتوريد الأدوات الصناعية المعتمدة، إلى خدمات الآبار وعمليات المنبع والمصب.',
  'p2': 'نمثّل الجسر المحلي الموثوق بين الخبرة الدولية والعمليات النفطية الليبية، من خلال شراكات فاعلة في أوروبا وآسيا والبحر المتوسط، لجلب أفضل التقنيات والخدمات النفطية العالمية إلى قطاع النفط الليبي.',
  'p3': 'والفرق جوهري. الوسيط يمرّر الاستفسار ويضيف هامشه. أما الجسر فيحتفظ بالمخزون داخل البلاد، ويحمل تفويض المصنّع، ويعبّئ طاقم الشريك، ويقف خلف العمل والحفارة تنتظر.',
},
'about_mv': [
  dict(k='رسالتنا', v='تقديم حلول طاقة وحلول صناعية موثوقة مصمّمة لقطاع النفط والغاز الليبي المتنامي — بجلب أدوات عالمية المستوى ومعايير سلامة دولية للمشغّلين العاملين هنا.'),
  dict(k='رؤيتنا', v='أن نكون قوة رائدة في قطاع الطاقة الليبي، وأن نُقاس بالمعايير نفسها التي يطبّقها أي مشغّل في أي مكان آخر من العالم.'),
],
'about_vals_h': 'ما لا نساوم عليه',
'about_vals': [
  dict(n='01', h='السلامة', p='ثقافة سلامة بلا تنازل. أدوات معتمدة، وأطقم مؤهلة، والشهادة متاحة قبل بدء العمل — لا بعد أن يطلبها التدقيق.'),
  dict(n='02', h='الجودة', p='معدات دقيقة ومعتمدة تُورَّد بوثائق المصنّع كاملة. لا بدائل معاد تغليفها، ولا استيراد مواز.'),
  dict(n='03', h='النزاهة', p='شركاء بالاسم، واتفاقيات مؤرّخة، ونطاق عمل نستطيع تنفيذه فعلاً. وإن كان العمل خارج ما نضمنه، نقولها بوضوح.'),
  dict(n='04', h='الشراكة', p='علاقات مبنية على الثقة لا على الصفقات. المشغّلون هنا يعملون مع الأشخاص أنفسهم لعقود — ونحن ننوي أن نكون منهم.'),
],
'about_tl_h': 'كيف يسير العمل فعلياً',
'about_tl': [
  dict(b='الخطوة 01', h='المواصفة', p='ترسل تصنيف المنطقة الخطرة والمعيار والكمية ونقطة التسليم. ولخدمات الآبار: برنامج البئر والتكوين.'),
  dict(b='الخطوة 02', h='عرض سعر بشهادة', p='نعود بالمراجع الدقيقة وشهادة المصنّع مرفقة، والتوفر من مخزون طرابلس، وسعر تسليم نهائي — لا سعراً استرشادياً.'),
  dict(b='الخطوة 03', h='الاستيراد والتخليص والنقل', p='إن لم يكن الصنف في المخزون، نتولى الاستيراد والتخليص الجمركي والنقل الداخلي بأنفسنا. جهة مسؤولة واحدة، لا سلسلة وسطاء.'),
  dict(b='الخطوة 04', h='التعبئة', p='في خدمات الآبار، يُعبَّأ طاقم الشريك وتجهيزاته إلى موقع الحفر تحت عقدنا ومعيار السلامة الخاص بنا.'),
  dict(b='الخطوة 05', h='بعد العمل', p='الضمان والمعايرة وإعادة الطلب من المكتب نفسه الذي أصدر العرض. من باعك هو من يردّ على الهاتف.'),
],

'contact_head': {'h': 'تواصل مع المكتب المختص.',
                 'lede': 'وجّه استفسارك مباشرة إلى الفريق الذي يتولاه. دون بريد عام، ودون سلسلة تحويلات.'},
'desks_h': 'المكاتب المباشرة',
'desks': [
  dict(b='الأدوات المعتمدة وEGA Master', s='tools@remalnahya.com'),
  dict(b='المشتريات التقنية', s='procurement@remalnahya.com'),
  dict(b='خدمات الآبار', s='wellservices@remalnahya.com'),
  dict(b='المسح والفحص بالمسيّرات', s='survey@remalnahya.com'),
],
'desks_note': 'توجيه مقترح. وإلى أن تُفعّل صناديق الأقسام، تُحوَّل الأربعة جميعاً إلى info@remalnahya.com.',
'contact_rows_h': 'المقر الرئيسي',
'form_h': 'اطلب عرض سعر',
'form_lede': 'أخبرنا بما تحتاجه وإلى أين يتجه. نردّ خلال يوم عمل واحد.',
'form': dict(name='الاسم الكامل', company='الشركة', email='البريد الإلكتروني', phone='الهاتف',
             dept='نوع الاستفسار', msg='ما الذي تحتاجه؟',
             msg_ph='تصنيف المنطقة، المعيار، الكميات، نقطة التسليم — أو برنامج البئر.',
             file='أرفق مواصفة أو جدول كميات', file_hint='PDF أو XLSX أو CSV أو DWG — حتى 20 ميغابايت. اختياري.',
             ph_name='أحمد ال…', ph_co='اسم المشغّل أو المقاول',
             submit='إرسال الاستفسار',
             ok='شكراً لك. تم تسجيل استفسارك وتوجيهه إلى المكتب المختص، وسنردّ خلال يوم عمل واحد. (هذا نموذج تجريبي، ولم تُرسَل أي رسالة فعلياً.)',
             note='لا نشارك تفاصيل الاستفسارات مع أي طرف ثالث.'),
'form_depts': ['الأدوات المعتمدة وEGA Master', 'المشتريات التقنية', 'خدمات الآبار', 'المسح بالمسيّرات', 'شراكة أو توريد', 'موضوع آخر'],

'foot': {
  'about': 'شركة خدمات نفطية ليبية: التوزيع الحصري لـ EGA Master، والمشتريات التقنية، وخدمات الآبار بالتعاون مع شركاء دوليين.',
  'c1': 'الشركة', 'c2': 'الخدمات', 'c3': 'تواصل معنا',
  'legal': '© 2026 رمال ناهية للخدمات النفطية. جميع الحقوق محفوظة.',
  'built': 'تصميم مقترح — أُعدّ لشركة رمال ناهية، 2026',
},
'foot_services': [('ega-master', 'أدوات EGA Master'), ('services', 'المشتريات التقنية'),
                  ('well-services', 'خدمات الآبار'), ('well-services', 'المسح بالمسيّرات')],
'skip': 'تخطَّ إلى المحتوى',
}


# ============================================================== SERVICE CATALOGUE
# cat: tools | procurement | wells | drone
SERVICES = [
 # ---- certified tools
 dict(cat='tools', icon='spark',
   en=dict(h='Non-sparking hand tools', p='Copper-beryllium and aluminium-bronze wrenches, hammers, sockets, chisels and scrapers that will not produce an incendive spark on impact in a zoned area.',
           specs=['Cu-Be', 'Al-Bronze', 'Zone 0/1/2'], by='EGA Master'),
   ar=dict(h='الأدوات اليدوية غير الشرارية', p='مفاتيح ومطارق ولقم وأزاميل وكاشطات من النحاس-بريليوم والبرونز الألومنيومي لا تولّد شرراً قادراً على الإشعال عند الارتطام في المناطق المصنّفة.',
           specs=['Cu-Be', 'Al-Bronze', 'Zone 0/1/2'], by='EGA Master')),
 dict(cat='tools', icon='shield',
   en=dict(h='ATEX certified safety sets', p='Pre-assembled maintenance kits for hazardous-area work, supplied as a certified set with a documented tool list and certification per kit.',
           specs=['ATEX', 'IECEx', 'Kitted'], by='EGA Master'),
   ar=dict(h='أطقم السلامة المعتمدة ATEX', p='أطقم صيانة مجهّزة مسبقاً للعمل في المناطق الخطرة، تُورَّد كطقم معتمد مع قائمة أدوات موثّقة وشهادة لكل طقم.',
           specs=['ATEX', 'IECEx', 'أطقم'], by='EGA Master')),
 dict(cat='tools', icon='bolt',
   en=dict(h='1000V insulated tools', p='VDE-tested insulated hand tools for live electrical work, including dual-rated tools that are both 1000V insulated and non-sparking.',
           specs=['VDE', '1000V', 'Dual-hazard'], by='EGA Master'),
   ar=dict(h='أدوات معزولة 1000 فولت', p='أدوات يدوية معزولة ومختبرة وفق VDE للأعمال الكهربائية الحية، تشمل أدوات مزدوجة التصنيف: معزولة 1000 فولت وغير شرارية معاً.',
           specs=['VDE', '1000V', 'خطورة مزدوجة'], by='EGA Master')),
 dict(cat='tools', icon='torque',
   en=dict(h='Hydraulic torque & tensioning', p='Hydraulic torque wrenches, bolt tensioners, pullers and presses for flange management and critical bolted joints, with calibrated torque control.',
           specs=['Calibrated', 'Flange management'], by='EGA Master'),
   ar=dict(h='العزم والشدّ الهيدروليكي', p='مفاتيح عزم هيدروليكية وشادّات براغي وسحّابات ومكابس لإدارة الفلنجات والوصلات الحرجة، مع ضبط عزم معاير.',
           specs=['معايرة', 'إدارة الفلنجات'], by='EGA Master')),
 dict(cat='tools', icon='ruler',
   en=dict(h='Pipe tools & machines', p='Pipe wrenches, cutters, threading and bevelling machines and tube benders for pipeline, refinery and plant fabrication.',
           specs=['Threading', 'Bevelling', 'Bending'], by='EGA Master'),
   ar=dict(h='أدوات وماكينات الأنابيب', p='مفاتيح أنابيب وقاطعات وماكينات تسنين وشطب وثنّايات لأعمال خطوط الأنابيب والمصافي وتصنيع المنشآت.',
           specs=['تسنين', 'شطب', 'ثني'], by='EGA Master')),
 dict(cat='tools', icon='box',
   en=dict(h='Tool control & 5S kitting', p='Foam-cut trays and shadow boards that make a missing tool visible instantly — turning a tool count into dropped-object prevention.',
           specs=['5S', 'Shadow boards', 'Foam cut'], by='EGA Master'),
   ar=dict(h='ضبط العدد وأطقم 5S', p='صواني إسفنجية مقصوصة ولوحات ظلّية تُظهر الأداة المفقودة فوراً — لتتحول عملية الجرد إلى منع لحوادث سقوط الأدوات.',
           specs=['5S', 'لوحات ظلّية', 'إسفنج مقصوص'], by='EGA Master')),
 dict(cat='tools', icon='layers',
   en=dict(h='Non-magnetic & titanium tools', p='Titanium and non-magnetic tooling for work around sensitive instrumentation, magnetic survey equipment and MWD tooling.',
           specs=['Titanium', 'Non-magnetic'], by='EGA Master'),
   ar=dict(h='أدوات غير مغناطيسية وتيتانيوم', p='أدوات من التيتانيوم وغير مغناطيسية للعمل قرب الأجهزة الحساسة ومعدات المسح المغناطيسي وأدوات MWD.',
           specs=['تيتانيوم', 'غير مغناطيسية'], by='EGA Master')),
 dict(cat='tools', icon='caliper',
   en=dict(h='Measuring & calibration', p='Precision measuring instruments plus calibration and re-certification services, so torque and measurement equipment stays inside its certificate.',
           specs=['Calibration', 'Re-certification'], by='EGA Master'),
   ar=dict(h='القياس والمعايرة', p='أجهزة قياس دقيقة مع خدمات المعايرة وإعادة الاعتماد، لتبقى معدات العزم والقياس ضمن نطاق شهاداتها.',
           specs=['معايرة', 'إعادة اعتماد'], by='EGA Master')),

 # ---- procurement
 dict(cat='procurement', icon='search',
   en=dict(h='Sourcing & vendor qualification', p='Identifying and qualifying suppliers against your specification and the applicable standard, so what arrives is what the specification actually called for.',
           specs=['Spec matching', 'Vendor audit'], by=''),
   ar=dict(h='تأمين المصادر وتأهيل الموردين', p='تحديد الموردين وتأهيلهم وفق مواصفتك والمعيار المعمول به، ليصل ما طلبته المواصفة فعلاً لا ما يقاربه.',
           specs=['مطابقة المواصفة', 'تدقيق الموردين'], by='')),
 dict(cat='procurement', icon='cart',
   en=dict(h='Industrial tool supply', p='Securing and supplying industrial tools beyond the EGA Master range where a project specification calls for a particular manufacturer.',
           specs=['Multi-brand', 'Spec-driven'], by=''),
   ar=dict(h='توريد الأدوات الصناعية', p='تأمين وتوريد الأدوات الصناعية خارج مجموعة EGA Master حين تستدعي مواصفة المشروع مصنّعاً بعينه.',
           specs=['متعدد العلامات', 'حسب المواصفة'], by='')),
 dict(cat='procurement', icon='cert',
   en=dict(h='Field consumables & PPE', p='Wellsite consumables, personal protective equipment and rig-floor supplies, replenished on a schedule rather than an emergency.',
           specs=['PPE', 'Consumables', 'Scheduled'], by=''),
   ar=dict(h='مستلزمات الحقل ومعدات الوقاية', p='مستلزمات موقع البئر ومعدات الوقاية الشخصية ولوازم أرضية الحفارة، بتجديد مجدول لا طارئ.',
           specs=['وقاية شخصية', 'مستلزمات', 'مجدول'], by='')),
 dict(cat='procurement', icon='globe',
   en=dict(h='Import & customs clearance', p='Import documentation, customs clearance and port handling managed in-house — one accountable party instead of a chain of forwarders.',
           specs=['Documentation', 'Clearance', 'Ports'], by=''),
   ar=dict(h='الاستيراد والتخليص الجمركي', p='مستندات الاستيراد والتخليص الجمركي والمناولة في الموانئ بإدارتنا المباشرة — جهة مسؤولة واحدة بدل سلسلة وسطاء.',
           specs=['المستندات', 'التخليص', 'الموانئ'], by='')),
 dict(cat='procurement', icon='truck',
   en=dict(h='Inland transport to wellsite', p='Delivery from the Tripoli warehouse to the rig site or facility, including the Sirte, Murzuq and Ghadames basins.',
           specs=['Tripoli → site', 'All basins'], by=''),
   ar=dict(h='النقل الداخلي إلى موقع البئر', p='التسليم من مخزن طرابلس إلى موقع الحفر أو المنشأة، بما يشمل أحواض سرت ومرزق وغدامس.',
           specs=['طرابلس ← الموقع', 'كل الأحواض'], by='')),
 dict(cat='procurement', icon='link',
   en=dict(h='After-sales, warranty & calibration', p='Warranty administration, calibration scheduling and re-ordering handled by the same desk that issued the quote.',
           specs=['Warranty', 'Calibration', 'Re-order'], by=''),
   ar=dict(h='ما بعد البيع والضمان والمعايرة', p='إدارة الضمان وجدولة المعايرة وإعادة الطلب من المكتب نفسه الذي أصدر عرض السعر.',
           specs=['الضمان', 'المعايرة', 'إعادة الطلب'], by='')),

 # ---- well services
 dict(cat='wells', icon='layers',
   en=dict(h='Primary & remedial cementing', p='Zonal isolation and casing support from spud through to remedial squeeze work, executed to a pressure rating of 15,000 psi.',
           specs=['15,000 psi', 'Squeeze', 'Zonal isolation'], by='Rompetrol Well Services'),
   ar=dict(h='التسمنت الأولي والعلاجي', p='عزل الطبقات ودعم أعمدة التغليف من بداية الحفر حتى أعمال الحقن العلاجي، بضغط معتمد يصل إلى 15,000 psi.',
           specs=['15,000 psi', 'حقن علاجي', 'عزل الطبقات'], by='Rompetrol Well Services')),
 dict(cat='wells', icon='flask',
   en=dict(h='Matrix acidising & stimulation', p='Formation-specific acid stimulation to restore and improve productivity in damaged or tight carbonate and sandstone reservoirs.',
           specs=['Matrix acid', 'Fracture acid'], by='Rompetrol Well Services'),
   ar=dict(h='التحفيز الحمضي للمصفوفة', p='تحفيز حمضي مصمّم حسب التكوين لاستعادة الإنتاجية وتحسينها في المكامن الكربوناتية والرملية المتضررة أو الضيقة.',
           specs=['تحميض مصفوفي', 'تحميض تكسيري'], by='Rompetrol Well Services')),
 dict(cat='wells', icon='drill',
   en=dict(h='Directional & extended-reach drilling', p='Directional and horizontal well construction, including extended-reach profiles for accessing reserves away from the surface location.',
           specs=['Directional', 'Horizontal', 'ERD'], by='SCA-Sichuan'),
   ar=dict(h='الحفر الاتجاهي وممتد المدى', p='إنشاء الآبار الاتجاهية والأفقية، بما فيها المسارات ممتدة المدى للوصول إلى احتياطيات بعيدة عن الموقع السطحي.',
           specs=['اتجاهي', 'أفقي', 'ممتد المدى'], by='SCA-Sichuan')),
 dict(cat='wells', icon='well',
   en=dict(h='Well completion & production optimisation', p='Running and setting the completion string, packers and downhole hardware, then optimising the well for sustained production.',
           specs=['Packers', 'Tubing', 'Optimisation'], by='SCA-Sichuan'),
   ar=dict(h='إتمام الآبار وتحسين الإنتاج', p='تشغيل وتثبيت عمود الإتمام والحواجز والمعدات الجوفية، ثم تحسين أداء البئر لإنتاج مستقر.',
           specs=['Packers', 'أنابيب الإنتاج', 'تحسين'], by='SCA-Sichuan')),
 dict(cat='wells', icon='clock',
   en=dict(h='Workover & well re-entry', p='Re-entry, rehabilitation and workover programmes on live and suspended wells to restore or extend productive life.',
           specs=['Re-entry', 'Rehabilitation'], by='SCA-Sichuan'),
   ar=dict(h='Workover وإعادة دخول الآبار', p='برامج إعادة الدخول وإعادة التأهيل والـ Workover على الآبار العاملة والمعلّقة لاستعادة العمر الإنتاجي أو إطالته.',
           specs=['إعادة دخول', 'إعادة تأهيل'], by='SCA-Sichuan')),
 dict(cat='wells', icon='flask',
   en=dict(h='Drilling fluids for HP formations', p='Drilling fluid design and management for high-pressure formations, maintaining wellbore stability and pressure control through the section.',
           specs=['High pressure', 'Mud engineering'], by='Rompetrol Well Services'),
   ar=dict(h='سوائل الحفر للتكوينات عالية الضغط', p='تصميم وإدارة سوائل الحفر للتكوينات عالية الضغط، للحفاظ على استقرار جدار البئر والتحكم في الضغط عبر المقطع.',
           specs=['ضغط عالٍ', 'هندسة الطين'], by='Rompetrol Well Services')),
 dict(cat='wells', icon='gauge',
   en=dict(h='Nitrogen & slickline services', p='Nitrogen lifting, purging and pressure testing, plus slickline conveyance for downhole tool runs and mechanical intervention.',
           specs=['N2 lifting', 'Slickline', 'Purging'], by='Rompetrol Well Services'),
   ar=dict(h='خدمات النيتروجين والـ Slickline', p='الرفع بالنيتروجين والتطهير واختبار الضغط، إضافة إلى النقل بالـ Slickline لتشغيل الأدوات الجوفية والتدخل الميكانيكي.',
           specs=['رفع بالنيتروجين', 'Slickline', 'تطهير'], by='Rompetrol Well Services')),
 dict(cat='wells', icon='drill',
   en=dict(h='Casing running & liner setting', p='Tubular running services — running, handling and setting casing and liner strings, with the equipment spread and crew mobilised to the rig.',
           specs=['Casing', 'Liner', 'Tubular handling'], by='CONSTECHNO AL'),
   ar=dict(h='تشغيل أعمدة التغليف وتثبيت الـ Liner', p='خدمات تشغيل الأنابيب — تشغيل ومناولة وتثبيت أعمدة التغليف والـ Liner، مع التجهيزات والطاقم المعبّأ إلى الحفارة.',
           specs=['التغليف', 'Liner', 'مناولة الأنابيب'], by='CONSTECHNO AL')),

 # ---- drone
 dict(cat='drone', icon='drone',
   en=dict(h='Drone pipeline inspection', p='Unmanned aerial survey of pipeline rights-of-way and facilities, covering remote spreads faster and more safely than a ground crew.',
           specs=['Right-of-way', 'Georeferenced'], by='Christof Industries'),
   ar=dict(h='فحص خطوط الأنابيب بالمسيّرات', p='مسح جوي بطائرات مسيّرة لمسارات خطوط الأنابيب والمنشآت، يغطي المساحات النائية أسرع وأكثر أماناً من الأطقم الأرضية.',
           specs=['مسار الخط', 'مرجعية جغرافية'], by='Christof Industries')),
 dict(cat='drone', icon='gauge',
   en=dict(h='Gas leak detection — VOC, H₂S, SO₂', p='Airborne sensors detecting volatile organic compound, hydrogen sulphide and sulphur dioxide releases while the asset stays in production.',
           specs=['VOC', 'H₂S', 'SO₂', 'No shutdown'], by='Christof Industries'),
   ar=dict(h='رصد تسربات الغازات — VOC وH₂S وSO₂', p='حساسات محمولة جواً ترصد انبعاثات المركبات العضوية المتطايرة وكبريتيد الهيدروجين وثاني أكسيد الكبريت والأصل ما زال في الإنتاج.',
           specs=['VOC', 'H₂S', 'SO₂', 'دون إيقاف'], by='Christof Industries')),
]
